### PR TITLE
Upgrade test runner from Racket 8.6 to Racket 8.9

### PR DESCRIPTION
**Pull request by fapdash**

### CODE REVIEW

**Comment by fapdash** [comment]
Also see https://github.com/exercism/racket/pull/264

**Review by ErikSchierboom — APPROVED** [review]

**Comment by fapdash** [comment]
Had hoped that I don't have to pull the container locally.. working on a fix.

**Comment by ErikSchierboom** [comment]
Thanks!

**Comment by ErikSchierboom** [comment]
> Had hoped that I don't have to pull the container locally.. working on a fix.

No worries, fixed it (I've done this lots of times)

**Comment by fapdash** [comment]
@ErikSchierboom Didn't see your message and you were quicker than me, my push didn't get through anymore :D Thanks!

**Comment by ErikSchierboom** [comment]
Sorry about that!

**Pull request merged**
