### PR TITLE
Upgrade runner to use Racket 8.11 CS

### PR DESCRIPTION
**Pull request by BNAndras**
Racket comes out every three months so the latest version came out four days ago.

### CODE REVIEW

**Comment by BNAndras** [comment]
Right, I forgot I didn't tweak the test runner script yet to sanitize file paths and those contain the Racket version number. Therefore, some of the expected results still contain a reference 8.10.

I'll take care of that this weekend.

**Comment by BNAndras** [comment]
I believe it's also time to switch from the Racket BC ('Before Chez') Docker image to a Racket CS ('Chez Scheme`) image. Racket CS has been the default implementation available since 8.0 was released two years ago. Judging from https://blog.racket-lang.org/2021/01/racket-status.html, the test runner should hopefully be faster. A student recently commented that list-ops was difficult to solve because there were some expensive tests being run.

**Comment by ErikSchierboom** [comment]
CI is failing. I think the expected values need to be updated.

**Comment by BNAndras** [comment]
Yeah, I'll take care of both issues.

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
